#!/bin/bash

cd && echo "export PATH='$PATH:/home/master/bin/npm'" >> .bash_aliases && echo "export NODE_PATH='$NODE_PATH:/home/master/bin/npm/lib/node_modules'" >> .bash_aliases && echo alias n='/home/master/bin/npm/lib/node_modules/bin/n' >> .bash_aliases && echo "export NODE_PATH=':/home/master/bin/npm/lib/node_modules' >> .bash_aliases && echo "export N_PREFIX=$HOME/.n" >> .bash_aliases && npm config set prefix "/home/master/bin/npm/lib/node_modules" && npm install n@latest -g && n latest
